In [102]:
import numpy as np
import pandas as pd

In [103]:
data = pd.read_csv('/content/drive/MyDrive/IPL2016.csv')
data.head()

Unnamed: 0  overall_sr  won
0           1  168.817204    1
1           2  165.432099    0
2           3  121.568627    0
3           4  149.541284    1
4           5  151.898734    0

In [104]:
X = np.array(data['overall_sr'])
y = np.array(data['won'])

In [105]:
X

array([168.8172043 , 165.43209877, 121.56862745, 149.5412844 ,
       151.89873418, 124.48979592, 112.        , 178.68852459,
       150.        ,  91.17647059, 222.42990654, 163.41463415,
       217.30769231, 113.20754717, 161.2244898 , 143.90243902])

In [106]:
X=X/300

In [107]:
X,y

(array([0.56272401, 0.55144033, 0.40522876, 0.49847095, 0.50632911,
        0.41496599, 0.37333333, 0.59562842, 0.5       , 0.30392157,
        0.74143302, 0.54471545, 0.72435897, 0.37735849, 0.53741497,
        0.4796748 ]),
 array([1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0]))

In [108]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))


In [113]:
sigmoid(20)

0.9999999979388463

In [119]:
print(len(y))

16


In [120]:
m=len(y)

In [133]:
def regression(X,y):
  alpha= 0.01
  iter = 100000
  intercept =0
  theta = np.random.randn()
  for i in range(iter):
    lmao =np.dot(X, theta)+ intercept
    y_pred= sigmoid(lmao)
    cost = -1/m * np.sum(y*np.log(y_pred) + (1-y)*np.log(1-y_pred))
    d_theta = (1/m) * np.dot(X.T, (y_pred - y))
    d_intercept = (1/m) * np.sum(y_pred - y)
    theta = theta - alpha * d_theta
    intercept = intercept - alpha * d_intercept
  return theta, intercept

In [134]:
theta, intercept = regression(X,y)
print(theta)
print(intercept)

11.012776940649571
-5.210769211289519


In [148]:
def result(qwerty):
    qwerty = qwerty / 300
    print("Chance of winning =", sigmoid(np.dot(theta, qwerty) + intercept) * 100, "%")


In [150]:
import ipywidgets as widgets
from IPython.display import display
strike_rate_input = widgets.Text(
    description="Strike Rate:",
    placeholder="Enter strike rate"
)
output = widgets.Output()

def on_button_click(b):
    with output:
        output.clear_output()
        strike_rate = int(strike_rate_input.value)
        print(result(strike_rate))
button = widgets.Button(description="Calculate brudda")
button.on_click(on_button_click)
display(strike_rate_input, button, output)


Text(value='', description='Strike Rate:', placeholder='Enter strike rate')

Button(description='Calculate brudda', style=ButtonStyle())

Output()